<?php

namespace Database\Seeders;

use App\Models\Persona;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class PersonasAprendicesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $personas = [
            [

                'tipo_documento' => NULL,
                'numero_documento' => '10073NULL71NULL7',
                'primer_nombre' => 'JOHN',
                'segundo_nombre' => 'EDUARD',
                'primer_apellido' => 'VELEZ',
                'segundo_apellido' => 'VASCA',
                'genero' => NULL,
                'telefono' => NULL,
                'celular' => '3005840510',
                'email' => 'eduardvelez066@gmail.com',
                'pais_id' => 1,
                'departamento_id' => NULL,
                'municipio_id' => 824,
                'direccion' => 'CALLE FALSA 123',
                'status' => 1,
                'user_create_id' => NULL,
                'user_edit_id' => NULL,
            ],
            [
                'tipo_documento' => NULL,
                'numero_documento' => '102NULL142202',
                'primer_nombre' => 'SAMUEL',
                'segundo_nombre' => 'RENE',
                'primer_apellido' => 'YEPES',
                'segundo_apellido' => 'RIVERA',
                'genero' => NULL,
                'telefono' => NULL,
                'celular' => '3173NULLNULL4234',
                'email' => 'rene2860NULL@gmail.com',
                'pais_id' => 1,
                'departamento_id' => 11,
                'municipio_id' => 100,
                'direccion' => 'AVENIDA SIEMPRE VIVA 742',
                'status' => 1,
                'user_create_id' => NULL,
                'user_edit_id' => NULL,
            ],
            [
                'tipo_documento' => NULL,
                'numero_documento' => '1041531NULL46',
                'primer_nombre' => 'DEYSON',
                'segundo_nombre' => 'DE JESUS',
                'primer_apellido' => 'URREGO',
                'segundo_apellido' => 'IBARRA',
                'genero' => NULL,
                'telefono' => NULL,
                'celular' => NULL,
                'email' => 'deysonurrego15NULL@gmail.com',
                'pais_id' => 1,
                'departamento_id' => 25,
                'municipio_id' => 824,
                'direccion' => 'CARRERA 7 # 12-34',
                'status' => 1,
                'user_create_id' => NULL,
                'user_edit_id' => NULL,
            ],
            [
                'tipo_documento' => NULL,
                'numero_documento' => '1041NULL76808',
                'primer_nombre' => 'JUAN',
                'segundo_nombre' => 'DAVID',
                'primer_apellido' => 'CASTRO',
                'segundo_apellido' => 'VILLARREAL',
                'genero' => NULL,
                'telefono' => NULL,
                'celular' => NULL,
                'email' => 'bahamutthero@gmail.com',
                'pais_id' => 1,
                'departamento_id' => 25,
                'municipio_id' => 126,
                'direccion' => 'CALLE 10 # 5-67 SUR',
                'status' => 1,
                'user_create_id' => NULL,
                'user_edit_id' => NULL,
            ],
            [
                'tipo_documento' => NULL,
                'numero_documento' => '1045228NULL03',
                'primer_nombre' => 'CAMILO',
                'segundo_nombre' => 'ANDRES',
                'primer_apellido' => 'HERNANDEZ',
                'segundo_apellido' => 'GONZALEZ',
                'genero' => NULL,
                'telefono' => NULL,
                'celular' => '3158644123',
                'email' => 'ch231322@gmail.com',
                'pais_id' => 1,
                'departamento_id' => NULL,
                'municipio_id' => 824,
                'direccion' => 'VIA PRINCIPAL KM 2',
                'status' => 1,
                'user_create_id' => NULL,
                'user_edit_id' => NULL,
            ],
            [
                'tipo_documento' => NULL,
                'numero_documento' => '10NULL2455166',
                'primer_nombre' => 'CARLOS',
                'segundo_nombre' => 'HERNAN',
                'primer_apellido' => 'MOLINA',
                'segundo_apellido' => 'ARENAS',
                'genero' => NULL,
                'telefono' => NULL,
                'celular' => '3007453220',
                'email' => 'Carloshernan2050@gmail.com',
                'pais_id' => 1,
                'departamento_id' => 5,
                'municipio_id' => 1,
                'direccion' => 'CALLE DEL SOL 45',
                'status' => 1,
                'user_create_id' => NULL,
                'user_edit_id' => NULL,
            ],
            [
                'tipo_documento' => NULL,
                'numero_documento' => '10NULLNULL735735',
                'primer_nombre' => 'NICOLAS',
                'segundo_nombre' => 'ANTONIO',
                'primer_apellido' => 'ARRIETA',
                'segundo_apellido' => 'LAGOS',
                'genero' => NULL,
                'telefono' => NULL,
                'celular' => '3165041NULL63',
                'email' => 'nicolasarrieta102NULL@gmail.com',
                'pais_id' => 1,
                'departamento_id' => 25,
                'municipio_id' => 824,
                'direccion' => 'CARRERA 50 # 80-25',
                'status' => 1,
                'user_create_id' => NULL,
                'user_edit_id' => NULL,
            ],
            [
                'tipo_documento' => NULL,
                'numero_documento' => '1120472282',
                'primer_nombre' => 'KAREN',
                'segundo_nombre' => 'JULIETH',
                'primer_apellido' => 'GONZALEZ',
                'segundo_apellido' => 'FERREIRA',
                'genero' => NULL,
                'telefono' => NULL,
                'celular' => NULL,
                'email' => 'kf8636557@gmail.com',
                'pais_id' => 1,
                'departamento_id' => 68,
                'municipio_id' => 1,
                'direccion' => 'CALLE 30 # 15-20',
                'status' => 1,
                'user_create_id' => NULL,
                'user_edit_id' => NULL,
            ],
            [
                'tipo_documento' => NULL,
                'numero_documento' => '1120558047',
                'primer_nombre' => 'JEFERSON',
                'segundo_nombre' => 'ALEXANDER',
                'primer_apellido' => 'ALVAREZ',
                'segundo_apellido' => 'RODRIGUEZ',
                'genero' => NULL,
                'telefono' => NULL,
                'celular' => '3218726683',
                'email' => 'mymotre213@gmail.com',
                'pais_id' => 1,
                'departamento_id' => 25,
                'municipio_id' => 824,
                'direccion' => 'AVENIDA LOS PINOS 10',
                'status' => 1,
                'user_create_id' => NULL,
                'user_edit_id' => NULL,
            ],
            [
                'tipo_documento' => NULL,
                'numero_documento' => '112055NULL248',
                'primer_nombre' => 'ALEX',
                'segundo_nombre' => 'DAVID',
                'primer_apellido' => 'VELANDIA',
                'segundo_apellido' => 'PEREZ',
                'genero' => NULL,
                'telefono' => NULL,
                'celular' => '3001111111',
                'email' => 'adavidvelandiap@gmail.com',
                'pais_id' => 1,
                'departamento_id' => 8,
                'municipio_id' => 1,
                'direccion' => 'VIA AL MAR KM 1',
                'status' => 1,
                'user_create_id' => NULL,
                'user_edit_id' => NULL,
            ],
            [
                'tipo_documento' => NULL,
                'numero_documento' => '1120561072',
                'primer_nombre' => 'RONALD',
                'segundo_nombre' => NULL,
                'primer_apellido' => 'BEJARANO',
                'segundo_apellido' => 'BARBOSA',
                'genero' => NULL,
                'telefono' => NULL,
                'celular' => '3104708132',
                'email' => 'ronaldbejarano147@gmail.com',
                'pais_id' => 1,
                'departamento_id' => 25,
                'municipio_id' => 824,
                'direccion' => 'CALLE 20 # 3-50',
                'status' => 1,
                'user_create_id' => NULL,
                'user_edit_id' => NULL,
            ],
            [
                'tipo_documento' => NULL,
                'numero_documento' => '112056133NULL',
                'primer_nombre' => 'JHON',
                'segundo_nombre' => 'DEIVID',
                'primer_apellido' => 'ROJAS',
                'segundo_apellido' => 'RODRIGUEZ',
                'genero' => NULL,
                'telefono' => NULL,
                'celular' => '315361627NULL',
                'email' => 'jhondeividrojasrodriguez@gmail.com',
                'pais_id' => 1,
                'departamento_id' => 76,
                'municipio_id' => 1,
                'direccion' => 'CALLE ANCHA 12',
                'status' => 1,
                'user_create_id' => NULL,
                'user_edit_id' => NULL,
            ],
            [
                'tipo_documento' => NULL,
                'numero_documento' => '1120561421',
                'primer_nombre' => 'CRISTIAN',
                'segundo_nombre' => 'YAHIR',
                'primer_apellido' => 'MONTENEGRO',
                'segundo_apellido' => 'MORENO',
                'genero' => NULL,
                'telefono' => NULL,
                'celular' => '32456NULL1425',
                'email' => 'yahirsinmoreno@gmail.com',
                'pais_id' => 1,
                'departamento_id' => 25,
                'municipio_id' => 824,
                'direccion' => 'CALLE 1 # 1-1',
                'status' => 1,
                'user_create_id' => NULL,
                'user_edit_id' => NULL,
            ],
            [
                'tipo_documento' => NULL,
                'numero_documento' => '1120578120',
                'primer_nombre' => 'HERNAN',
                'segundo_nombre' => 'DAVID',
                'primer_apellido' => 'CIFUENTES',
                'segundo_apellido' => 'ARENAS',
                'genero' => NULL,
                'telefono' => NULL,
                'celular' => NULL,
                'email' => 'hernanorion@hotmail.com',
                'pais_id' => 1,
                'departamento_id' => 15,
                'municipio_id' => 1,
                'direccion' => 'KILOMETRO 5 CARRETERA CENTRAL',
                'status' => 1,
                'user_create_id' => NULL,
                'user_edit_id' => NULL,
            ],
            [
                'tipo_documento' => NULL,
                'numero_documento' => '1120254287',
                'primer_nombre' => 'NESTOR',
                'segundo_nombre' => 'DAVID',
                'primer_apellido' => 'PORRAS',
                'segundo_apellido' => 'SUAZA',
                'genero' => NULL,
                'telefono' => NULL,
                'celular' => NULL,
                'email' => 'dsuaza52@gmail.com',
                'pais_id' => 1,
                'departamento_id' => 25,
                'municipio_id' => 824,
                'direccion' => 'BARRIO EL CENTRO CR 8 # 2-30',
                'status' => 1,
                'user_create_id' => NULL,
                'user_edit_id' => NULL,
            ],
            [
                'tipo_documento' => NULL,
                'numero_documento' => '1073813055',
                'primer_nombre' => 'JOSE',
                'segundo_nombre' => 'DAVID',
                'primer_apellido' => 'HERNANDEZ',
                'segundo_apellido' => 'NAVAJA',
                'genero' => NULL,
                'telefono' => NULL,
                'celular' => '3204615126',
                'email' => 'jdhernandezn11@gmail.com',
                'pais_id' => 1,
                'departamento_id' => 50,
                'municipio_id' => 1,
                'direccion' => 'CALLE 40 # 25-10',
                'status' => 1,
                'user_create_id' => NULL,
                'user_edit_id' => NULL,
            ],
            [
                'tipo_documento' => NULL,
                'numero_documento' => '1120563250',
                'primer_nombre' => 'HECTOR',
                'segundo_nombre' => 'KALET',
                'primer_apellido' => 'CASTAÑEDA',
                'segundo_apellido' => 'MESA',
                'genero' => NULL,
                'telefono' => NULL,
                'celular' => '3222230184',
                'email' => 'kalethcastanedaNULL66@gmail.com',
                'pais_id' => 1,
                'departamento_id' => 25,
                'municipio_id' => 824,
                'direccion' => 'AVENIDA EL DORADO 100',
                'status' => 1,
                'user_create_id' => NULL,
                'user_edit_id' => NULL,
            ],
            [
                'tipo_documento' => NULL,
                'numero_documento' => '1120564156',
                'primer_nombre' => 'LUIS',
                'segundo_nombre' => 'FELIPE',
                'primer_apellido' => 'CORTES',
                'segundo_apellido' => 'MORENO',
                'genero' => NULL,
                'telefono' => NULL,
                'celular' => '3188NULL63657',
                'email' => 'elpipessj@gmail.com',
                'pais_id' => 1,
                'departamento_id' => 23,
                'municipio_id' => 1,
                'direccion' => 'CARRERA 1 # 1-1',
                'status' => 1,
                'user_create_id' => NULL,
                'user_edit_id' => NULL,
            ],
            [
                'tipo_documento' => NULL,
                'numero_documento' => '1120564168',
                'primer_nombre' => 'CRISTIAN',
                'segundo_nombre' => 'CAMILO',
                'primer_apellido' => 'CAMACHO',
                'segundo_apellido' => 'MORALES',
                'genero' => NULL,
                'telefono' => NULL,
                'celular' => NULL,
                'email' => 'camilocamacho25@icloud.com',
                'pais_id' => 1,
                'departamento_id' => 25,
                'municipio_id' => 824,
                'direccion' => 'CALLE DE LA LUNA 25',
                'status' => 1,
                'user_create_id' => NULL,
                'user_edit_id' => NULL,
            ],
            [
                'tipo_documento' => NULL,
                'numero_documento' => '1120564712',
                'primer_nombre' => 'KEVIN',
                'segundo_nombre' => 'SANTIAGO',
                'primer_apellido' => 'PRADA',
                'segundo_apellido' => 'CASTELLANOS',
                'genero' => NULL,
                'telefono' => NULL,
                'celular' => NULL,
                'email' => 'santicastellanos2017@gmail.com',
                'pais_id' => 1,
                'departamento_id' => 11,
                'municipio_id' => 100,
                'direccion' => 'DIAGONAL 45 # 8-NULL0',
                'status' => 1,
                'user_create_id' => NULL,
                'user_edit_id' => NULL,
            ],
            [
                'tipo_documento' => NULL,
                'numero_documento' => '1120565087',
                'primer_nombre' => 'JHON',
                'segundo_nombre' => 'DEIBY',
                'primer_apellido' => 'OLARTE',
                'segundo_apellido' => 'BENITES',
                'genero' => NULL,
                'telefono' => NULL,
                'celular' => '316253574NULL',
                'email' => 'deibyolarte24@gmail.com',
                'pais_id' => 1,
                'departamento_id' => 25,
                'municipio_id' => 824,
                'direccion' => 'CALLE LOS ROBLES 7',
                'status' => 1,
                'user_create_id' => NULL,
                'user_edit_id' => NULL,
            ],
            [
                'tipo_documento' => NULL,
                'numero_documento' => '1120565281',
                'primer_nombre' => 'LISSETH',
                'segundo_nombre' => 'KATERINE',
                'primer_apellido' => 'RIVAS',
                'segundo_apellido' => 'BEDOYA',
                'genero' => NULL,
                'telefono' => NULL,
                'celular' => '3215451646',
                'email' => 'lissethrivas1328@gmail.com',
                'pais_id' => 1,
                'departamento_id' => 66,
                'municipio_id' => 1,
                'direccion' => 'VIA AL PUEBLO KM 3',
                'status' => 1,
                'user_create_id' => NULL,
                'user_edit_id' => NULL,
            ],
            [
                'tipo_documento' => NULL,
                'numero_documento' => '1120566066',
                'primer_nombre' => 'DANIEL',
                'segundo_nombre' => 'SANTIAGO',
                'primer_apellido' => 'JOVEL',
                'segundo_apellido' => 'REYES',
                'genero' => NULL,
                'telefono' => NULL,
                'celular' => '3001111112',
                'email' => 'marielareyesamado440@gmail.com',
                'pais_id' => 1,
                'departamento_id' => 25,
                'municipio_id' => 824,
                'direccion' => 'CALLE DE LAS FLORES 5',
                'status' => 1,
                'user_create_id' => NULL,
                'user_edit_id' => NULL,
            ],
            [
                'tipo_documento' => NULL,
                'numero_documento' => '1120255461',
                'primer_nombre' => 'MICHAEL',
                'segundo_nombre' => 'ORLANDO',
                'primer_apellido' => 'SANTOYA',
                'segundo_apellido' => 'PARRA',
                'genero' => NULL,
                'telefono' => NULL,
                'celular' => NULL,
                'email' => 'dilansantoya450@gmail.com',
                'pais_id' => 1,
                'departamento_id' => 47,
                'municipio_id' => 1,
                'direccion' => 'AVENIDA SIEMPRE ABIERTA 24/7',
                'status' => 1,
                'user_create_id' => NULL,
                'user_edit_id' => NULL,
            ],
            [
                'tipo_documento' => NULL,
                'numero_documento' => '1120255574',
                'primer_nombre' => 'VINCEN',
                'segundo_nombre' => 'DAVID',
                'primer_apellido' => 'DONCEL',
                'segundo_apellido' => 'VELASQUEZ',
                'genero' => NULL,
                'telefono' => NULL,
                'celular' => '3212757330',
                'email' => 'vincentdoncelv@gmail.com',
                'pais_id' => 1,
                'departamento_id' => 25,
                'municipio_id' => 824,
                'direccion' => 'CALLE DEL RIO NULLNULL',
                'status' => 1,
                'user_create_id' => NULL,
                'user_edit_id' => NULL,
            ],
            [
                'tipo_documento' => NULL,
                'numero_documento' => '1120255651',
                'primer_nombre' => 'JHON',
                'segundo_nombre' => 'JAIRO',
                'primer_apellido' => 'SANTAMARIA',
                'segundo_apellido' => 'PORRAS',
                'genero' => NULL,
                'telefono' => NULL,
                'celular' => NULL,
                'email' => 'jhonjairosantamaria04NULL@gmail.com',
                'pais_id' => 1,
                'departamento_id' => 5,
                'municipio_id' => 1,
                'direccion' => 'BARRIO LA PAZ MZ 1 LT 2',
                'status' => 1,
                'user_create_id' => NULL,
                'user_edit_id' => NULL,
            ],
            [
                'tipo_documento' => NULL,
                'numero_documento' => '1120256052',
                'primer_nombre' => 'DANNA',
                'segundo_nombre' => 'KATHERIN',
                'primer_apellido' => 'VARGAS',
                'segundo_apellido' => 'RUIZ',
                'genero' => NULL,
                'telefono' => NULL,
                'celular' => NULL,
                'email' => 'Dannajin3@gmail.com',
                'pais_id' => 1,
                'departamento_id' => 25,
                'municipio_id' => 824,
                'direccion' => 'CALLE DEL PUERTO S/N',
                'status' => 1,
                'user_create_id' => NULL,
                'user_edit_id' => NULL,
            ],
            [
                'tipo_documento' => NULL,
                'numero_documento' => '1122NULL22NULL10',
                'primer_nombre' => 'MARIO',
                'segundo_nombre' => 'ALEXANDER',
                'primer_apellido' => 'CAÑOLA',
                'segundo_apellido' => 'CANO',
                'genero' => NULL,
                'telefono' => NULL,
                'celular' => NULL,
                'email' => 'marioalexandercanola@gmail.com',
                'pais_id' => 1,
                'departamento_id' => 11,
                'municipio_id' => 100,
                'direccion' => 'CARRERA 3 # 4-50',
                'status' => 1,
                'user_create_id' => NULL,
                'user_edit_id' => NULL,
            ],
        ];

        foreach ($personas as $persona) {
            Persona::create($persona);
        }

        //Se crean los usuarios y se les asigna el rol de aprendiz a las personas anteriores
        for($i = 4; $i < 32; $i++){
            $aprendiz = User::create([
                'email' => 'aprendiz'.$i.'@aprendiz.com',
                'password' => Hash::make('123456'),
                'status' => 1,
                'persona_id' => $i
            ]);

            $aprendiz->assignRole('APRENDIZ');
        }
    }
}