<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Inventario\Producto;

class ProductoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $productos = [
             [
                'producto' => 'PAPEL ABSORBENTE',
                'tipo_producto_id' => 28,
                'descripcion' => '',
                'peso' => 0,
                'unidad_medida_id' => 41,
                'cantidad' => 1.0,
                'codigo_barras' => '10000000001',
                'estado_producto_id' => 50,
                'categoria_id' => 62,
                'marca_id' => 81,
                'contrato_convenio_id' => 1,
                'ambiente_id' => 1,
                'proveedor_id' => 1,
                'fecha_vencimiento' => null,
                'imagen' => 'img/inventario/producto-default.png',
                'user_create_id' => 1, 
                'user_update_id' => 1,
            ],
            [
                'producto' => 'PAPEL FILTRO',
                'tipo_producto_id' => 28,
                'descripcion' => 'X 100 PIEZAS',
                'peso' => 0,
                'unidad_medida_id' => 42,
                'cantidad' => 3.0,
                'codigo_barras' => '10000000002',
                'estado_producto_id' => 50,
                'categoria_id' => 62,
                'marca_id' => null,
                'contrato_convenio_id' => 1,
                'ambiente_id' => 1,
                'proveedor_id' => 1,
                'fecha_vencimiento' => null,
                'imagen' => 'img/inventario/producto-default.png',
                'user_create_id' => 1, 
                'user_update_id' => 1,
            ],
            [
                'producto' => 'SAL DE COCINA',
                'tipo_producto_id' => 28,
                'descripcion' => 'No cuenta con empaque.',
                'peso' => 0,
                'unidad_medida_id' => 30,
                'cantidad' => 54.0,
                'codigo_barras' => '10000000003',
                'estado_producto_id' => 50,
                'categoria_id' => 62,
                'marca_id' => null,
                'contrato_convenio_id' => 1,
                'ambiente_id' => 1,
                'proveedor_id' => 1,
                'fecha_vencimiento' => null,
                'imagen' => 'img/inventario/producto-default.png',
                'user_create_id' => 1, 
                'user_update_id' => 1,
            ],
            [
                'producto' => 'MELAZA',
                'tipo_producto_id' => 28,
                'descripcion' => 'No cuenta con empaque etiquetado.',
                'peso' => 0,
                'unidad_medida_id' => 30,
                'cantidad' => 1270.0,
                'codigo_barras' => '10000000004',
                'estado_producto_id' => 50,
                'categoria_id' => 62,
                'marca_id' => null,
                'contrato_convenio_id' => 1,
                'ambiente_id' => 1,
                'proveedor_id' => 1,
                'fecha_vencimiento' => null,
                'imagen' => 'img/inventario/producto-default.png',
                'user_create_id' => 1, 
                'user_update_id' => 1,
            ],
            [
                'producto' => 'PARAFINA',
                'tipo_producto_id' => 28,
                'descripcion' => 'No cuenta con empaque etiquetado.',
                'peso' => 0,
                'unidad_medida_id' => 30,
                'cantidad' => 5412.0,
                'codigo_barras' => '10000000005',
                'estado_producto_id' => 50,
                'categoria_id' => 62,
                'marca_id' => null,
                'contrato_convenio_id' => 1,
                'ambiente_id' => 1,
                'proveedor_id' => 1,
                'fecha_vencimiento' => null,
                'imagen' => 'img/inventario/producto-default.png',
                'user_create_id' => 1, 
                'user_update_id' => 1,
            ],
            [
                'producto' => 'GRAVA DE ACUARIO',
                'tipo_producto_id' => 28,
                'descripcion' => 'Verde, naranja y blanca',
                'peso' => 0,
                'unidad_medida_id' => 32,
                'cantidad' => 92.5,
                'codigo_barras' => '10000000006',
                'estado_producto_id' => 50,
                'categoria_id' => 62,
                'marca_id' => 116,
                'contrato_convenio_id' => 1,
                'ambiente_id' => 1,
                'proveedor_id' => 1,
                'fecha_vencimiento' => null,
                'imagen' => 'img/inventario/producto-default.png',
                'user_create_id' => 1, 
                'user_update_id' => 1,
            ],
            [
                'producto' => 'PAPEL ALUMINIO',
                'tipo_producto_id' => 28,
                'descripcion' => '',
                'peso' => 0,
                'unidad_medida_id' => 43,
                'cantidad' => 250.0,
                'codigo_barras' => '10000000007',
                'estado_producto_id' => 50,
                'categoria_id' => 62,
                'marca_id' => 80,
                'contrato_convenio_id' => 1,
                'ambiente_id' => 1,
                'proveedor_id' => 1,
                'fecha_vencimiento' => null,
                'imagen' => 'img/inventario/producto-default.png',
                'user_create_id' => 1, 
                'user_update_id' => 1,
            ],
            [
                'producto' => 'ASERRÍN',
                'tipo_producto_id' => 28,
                'descripcion' => '',
                'peso' => 0,
                'unidad_medida_id' => 32,
                'cantidad' => 5.0,
                'codigo_barras' => '10000000008',
                'estado_producto_id' => 50,
                'categoria_id' => 62,
                'marca_id' => null,
                'contrato_convenio_id' => 1,
                'ambiente_id' => 1,
                'proveedor_id' => 1,
                'fecha_vencimiento' => null,
                'imagen' => 'img/inventario/producto-default.png',
                'user_create_id' => 1, 
                'user_update_id' => 1,
            ],
            [
                'producto' => 'TURBA',
                'tipo_producto_id' => 28,
                'descripcion' => '',
                'peso' => 0,
                'unidad_medida_id' => 32,
                'cantidad' => 0.0,
                'codigo_barras' => '10000000009',
                'estado_producto_id' => 50,
                'categoria_id' => 62,
                'marca_id' => null,
                'contrato_convenio_id' => 1,
                'ambiente_id' => 1,
                'proveedor_id' => 1,
                'fecha_vencimiento' => null,
                'imagen' => 'img/inventario/producto-default.png',
                'user_create_id' => 1, 
                'user_update_id' => 1,
            ],
            [
                'producto' => 'GRABA',
                'tipo_producto_id' => 28,
                'descripcion' => '',
                'peso' => 0,
                'unidad_medida_id' => 32,
                'cantidad' => 62.0,
                'codigo_barras' => '10000000010',
                'estado_producto_id' => 50,
                'categoria_id' => 62,
                'marca_id' => null,
                'contrato_convenio_id' => 1,
                'ambiente_id' => 1,
                'proveedor_id' => 1,
                'fecha_vencimiento' => null,
                'imagen' => 'img/inventario/producto-default.png',
                'user_create_id' => 1, 
                'user_update_id' => 1,
            ],
            [
                'producto' => 'ACONDICIONADOR ORGANICO DE SUELOS',
                'tipo_producto_id' => 28,
                'descripcion' => '',
                'peso' => 0,
                'unidad_medida_id' => 30,
                'cantidad' => 0.0,
                'codigo_barras' => '10000000011',
                'estado_producto_id' => 50,
                'categoria_id' => 62,
                'marca_id' => null,
                'contrato_convenio_id' => 1,
                'ambiente_id' => 1,
                'proveedor_id' => 1,
                'fecha_vencimiento' => null,
                'imagen' => 'img/inventario/producto-default.png',
                'user_create_id' => 1, 
                'user_update_id' => 1,
            ],
            [
                'producto' => 'REGLA MEDIDORA DE PH',
                'tipo_producto_id' => 28,
                'descripcion' => '',
                'peso' => 0,
                'unidad_medida_id' => 41,
                'cantidad' => 0.0,
                'codigo_barras' => '10000000012',
                'estado_producto_id' => 50,
                'categoria_id' => 62,
                'marca_id' => null,
                'contrato_convenio_id' => 1,
                'ambiente_id' => 1,
                'proveedor_id' => 1,
                'fecha_vencimiento' => null,
                'imagen' => 'img/inventario/producto-default.png',
                'user_create_id' => 1, 
                'user_update_id' => 1,
            ],
            [
                'producto' => 'PISETA 500 ML',
                'tipo_producto_id' => 28,
                'descripcion' => '',
                'peso' => 0,
                'unidad_medida_id' => 41,
                'cantidad' => 2.0,
                'codigo_barras' => '10000000013',
                'estado_producto_id' => 50,
                'categoria_id' => 66,
                'marca_id' => 78,
                'contrato_convenio_id' => 1,
                'ambiente_id' => 1,
                'proveedor_id' => 1,
                'fecha_vencimiento' => null,
                'imagen' => 'img/inventario/producto-default.png',
                'user_create_id' => 1, 
                'user_update_id' => 1,
            ],
            [
                'producto' => 'ATOMIZADORES',
                'tipo_producto_id' => 28,
                'descripcion' => '',
                'peso' => 0,
                'unidad_medida_id' => 41,
                'cantidad' => 3.0,
                'codigo_barras' => '10000000014',
                'estado_producto_id' => 50,
                'categoria_id' => 66,
                'marca_id' => null,
                'contrato_convenio_id' => 1,
                'ambiente_id' => 1,
                'proveedor_id' => 1,
                'fecha_vencimiento' => null,
                'imagen' => 'img/inventario/producto-default.png',
                'user_create_id' => 1, 
                'user_update_id' => 1,
            ],
            [
                'producto' => 'FRASCO SCHOT 500 ML',
                'tipo_producto_id' => 28,
                'descripcion' => '',
                'peso' => 0,
                'unidad_medida_id' => 41,
                'cantidad' => 1.0,
                'codigo_barras' => '10000000015',
                'estado_producto_id' => 50,
                'categoria_id' => 66,
                'marca_id' => 74,
                'contrato_convenio_id' => 1,
                'ambiente_id' => 1,
                'proveedor_id' => 1,
                'fecha_vencimiento' => null,
                'imagen' => 'img/inventario/producto-default.png',
                'user_create_id' => 1, 
                'user_update_id' => 1,
            ],
            [
                'producto' => 'FRASCO SCHOT 250 ML',
                'tipo_producto_id' => 28,
                'descripcion' => '',
                'peso' => 0,
                'unidad_medida_id' => 41,
                'cantidad' => 1.0,
                'codigo_barras' => '10000000016',
                'estado_producto_id' => 50,
                'categoria_id' => 66,
                'marca_id' => 74,
                'contrato_convenio_id' => 1,
                'ambiente_id' => 1,
                'proveedor_id' => 1,
                'fecha_vencimiento' => null,
                'imagen' => 'img/inventario/producto-default.png',
                'user_create_id' => 1, 
                'user_update_id' => 1,
            ],
            [
                'producto' => 'JARRA METALICA',
                'tipo_producto_id' => 28,
                'descripcion' => 'Jarra de un litro',
                'peso' => 0,
                'unidad_medida_id' => 41,
                'cantidad' => 1.0,
                'codigo_barras' => '10000000017',
                'estado_producto_id' => 50,
                'categoria_id' => 66,
                'marca_id' => null,
                'contrato_convenio_id' => 1,
                'ambiente_id' => 1,
                'proveedor_id' => 1,
                'fecha_vencimiento' => null,
                'imagen' => 'img/inventario/producto-default.png',
                'user_create_id' => 1, 
                'user_update_id' => 1,
            ],
            [
                'producto' => 'TUBOS PARA DENSIDAD',
                'tipo_producto_id' => 28,
                'descripcion' => 'Tubos de PVC',
                'peso' => 0,
                'unidad_medida_id' => 41,
                'cantidad' => 16.0,
                'codigo_barras' => '10000000018',
                'estado_producto_id' => 50,
                'categoria_id' => 66,
                'marca_id' => null,
                'contrato_convenio_id' => 1,
                'ambiente_id' => 1,
                'proveedor_id' => 1,
                'fecha_vencimiento' => null,
                'imagen' => 'img/inventario/producto-default.png',
                'user_create_id' => 1, 
                'user_update_id' => 1,
            ],
            [
                'producto' => 'CAJAS METALICAS PARA DENSIDAD',
                'tipo_producto_id' => 28,
                'descripcion' => '',
                'peso' => 0,
                'unidad_medida_id' => 41,
                'cantidad' => 10.0,
                'codigo_barras' => '10000000019',
                'estado_producto_id' => 50,
                'categoria_id' => 66,
                'marca_id' => null,
                'contrato_convenio_id' => 1,
                'ambiente_id' => 1,
                'proveedor_id' => 1,
                'fecha_vencimiento' => null,
                'imagen' => 'img/inventario/producto-default.png',
                'user_create_id' => 1, 
                'user_update_id' => 1,
            ],
            [
                'producto' => 'CAJA DE PLASTICO CON TAPA CON VOLUMEN DE 5L',
                'tipo_producto_id' => 28,
                'descripcion' => '',
                'peso' => 0,
                'unidad_medida_id' => 41,
                'cantidad' => 0.0,
                'codigo_barras' => '10000000020',
                'estado_producto_id' => 50,
                'categoria_id' => 66,
                'marca_id' => null,
                'contrato_convenio_id' => 1,
                'ambiente_id' => 1,
                'proveedor_id' => 1,
                'fecha_vencimiento' => null,
                'imagen' => 'img/inventario/producto-default.png',
                'user_create_id' => 1, 
                'user_update_id' => 1,
            ],
            [
                'producto' => 'BANDEJA METALICA',
                'tipo_producto_id' => 28,
                'descripcion' => '',
                'peso' => 0,
                'unidad_medida_id' => 41,
                'cantidad' => 1.0,
                'codigo_barras' => '10000000021',
                'estado_producto_id' => 50,
                'categoria_id' => 66,
                'marca_id' => null,
                'contrato_convenio_id' => 1,
                'ambiente_id' => 1,
                'proveedor_id' => 1,
                'fecha_vencimiento' => null,
                'imagen' => 'img/inventario/producto-default.png',
                'user_create_id' => 1, 
                'user_update_id' => 1,
            ],
            [
                'producto' => 'TARROS DE PLASTICO CON TAPA',
                'tipo_producto_id' => 28,
                'descripcion' => '2 tapas sin tarros',
                'peso' => 0,
                'unidad_medida_id' => 41,
                'cantidad' => 10.0,
                'codigo_barras' => '10000000022',
                'estado_producto_id' => 50,
                'categoria_id' => 66,
                'marca_id' => null,
                'contrato_convenio_id' => 1,
                'ambiente_id' => 1,
                'proveedor_id' => 1,
                'fecha_vencimiento' => null,
                'imagen' => 'img/inventario/producto-default.png',
                'user_create_id' => 1, 
                'user_update_id' => 1,
            ],
            [
                'producto' => 'EMBUDO',
                'tipo_producto_id' => 28,
                'descripcion' => 'EMBUDO PEQUEÑO DE PLASTICO',
                'peso' => 0,
                'unidad_medida_id' => 41,
                'cantidad' => 6.0,
                'codigo_barras' => '10000000023',
                'estado_producto_id' => 50,
                'categoria_id' => 66,
                'marca_id' => null,
                'contrato_convenio_id' => 1,
                'ambiente_id' => 1,
                'proveedor_id' => 1,
                'fecha_vencimiento' => null,
                'imagen' => 'img/inventario/producto-default.png',
                'user_create_id' => 1, 
                'user_update_id' => 1,
            ],
            [
                'producto' => 'GOTERO',
                'tipo_producto_id' => 28,
                'descripcion' => '',
                'peso' => 0,
                'unidad_medida_id' => 41,
                'cantidad' => 17.0,
                'codigo_barras' => '10000000024',
                'estado_producto_id' => 50,
                'categoria_id' => 66,
                'marca_id' => null,
                'contrato_convenio_id' => 1,
                'ambiente_id' => 1,
                'proveedor_id' => 1,
                'fecha_vencimiento' => null,
                'imagen' => 'img/inventario/producto-default.png',
                'user_create_id' => 1, 
                'user_update_id' => 1,
            ],
            [
                'producto' => 'ESPATULA',
                'tipo_producto_id' => 28,
                'descripcion' => '',
                'peso' => 0,
                'unidad_medida_id' => 41,
                'cantidad' => 5.0,
                'codigo_barras' => '10000000025',
                'estado_producto_id' => 50,
                'categoria_id' => 66,
                'marca_id' => null,
                'contrato_convenio_id' => 1,
                'ambiente_id' => 1,
                'proveedor_id' => 1,
                'fecha_vencimiento' => null,
                'imagen' => 'img/inventario/producto-default.png',
                'user_create_id' => 1, 
                'user_update_id' => 1,
            ],
            [
                'producto' => 'AGITADOR',
                'tipo_producto_id' => 28,
                'descripcion' => 'Varillas en vidrio.',
                'peso' => 0,
                'unidad_medida_id' => 41,
                'cantidad' => 5.0,
                'codigo_barras' => '10000000026',
                'estado_producto_id' => 50,
                'categoria_id' => 66,
                'marca_id' => null,
                'contrato_convenio_id' => 1,
                'ambiente_id' => 1,
                'proveedor_id' => 1,
                'fecha_vencimiento' => null,
                'imagen' => 'img/inventario/producto-default.png',
                'user_create_id' => 1, 
                'user_update_id' => 1,
            ],
            [
                'producto' => 'CUCHARA',
                'tipo_producto_id' => 28,
                'descripcion' => 'Cucharas medidoras en plástico.',
                'peso' => 0,
                'unidad_medida_id' => 41,
                'cantidad' => 8.0,
                'codigo_barras' => '10000000027',
                'estado_producto_id' => 50,
                'categoria_id' => 66,
                'marca_id' => null,
                'contrato_convenio_id' => 1,
                'ambiente_id' => 1,
                'proveedor_id' => 1,
                'fecha_vencimiento' => null,
                'imagen' => 'img/inventario/producto-default.png',
                'user_create_id' => 1, 
                'user_update_id' => 1,
            ],
            [
                'producto' => 'TABLA MUNSELL',
                'tipo_producto_id' => 28,
                'descripcion' => '',
                'peso' => 0,
                'unidad_medida_id' => 41,
                'cantidad' => 1.0,
                'codigo_barras' => '10000000028',
                'estado_producto_id' => 50,
                'categoria_id' => 66,
                'marca_id' => null,
                'contrato_convenio_id' => 1,
                'ambiente_id' => 1,
                'proveedor_id' => 1,
                'fecha_vencimiento' => null,
                'imagen' => 'img/inventario/producto-default.png',
                'user_create_id' => 1, 
                'user_update_id' => 1,
            ],
            [
                'producto' => 'FUNGICIDA',
                'tipo_producto_id' => 28,
                'descripcion' => 'No cuentan con etiquetado.',
                'peso' => 0,
                'unidad_medida_id' => 36,
                'cantidad' => 500.0,
                'codigo_barras' => '10000000029',
                'estado_producto_id' => 50,
                'categoria_id' => 65,
                'marca_id' => null,
                'contrato_convenio_id' => 1,
                'ambiente_id' => 1,
                'proveedor_id' => 1,
                'fecha_vencimiento' => null,
                'imagen' => 'img/inventario/producto-default.png',
                'user_create_id' => 1, 
                'user_update_id' => 1,
            ],
            [
                'producto' => 'AGUA ESTERÍL PARA INYECCIÓN',
                'tipo_producto_id' => 28,
                'descripcion' => '',
                'peso' => 0,
                'unidad_medida_id' => 36,
                'cantidad' => 0.0,
                'codigo_barras' => '10000000030',
                'estado_producto_id' => 50,
                'categoria_id' => 65,
                'marca_id' => null,
                'contrato_convenio_id' => 1,
                'ambiente_id' => 1,
                'proveedor_id' => 1,
                'fecha_vencimiento' => null,
                'imagen' => 'img/inventario/producto-default.png',
                'user_create_id' => 1, 
                'user_update_id' => 1,
            ],
            [
                'producto' => 'AGUA OXIGENADA',
                'tipo_producto_id' => 28,
                'descripcion' => 'Cuenta con 20 mililitros',
                'peso' => 0,
                'unidad_medida_id' => 36,
                'cantidad' => 0,
                'codigo_barras' => '10000000031',
                'estado_producto_id' => 50,
                'categoria_id' => 65,
                'marca_id' => 102,
                'contrato_convenio_id' => 1,
                'ambiente_id' => 1,
                'proveedor_id' => 1,
                'fecha_vencimiento' => null,
                'imagen' => 'img/inventario/producto-default.png',
                'user_create_id' => 1, 
                'user_update_id' => 1,
            ],
            [
                'producto' => 'YESO AGRICOLA',
                'tipo_producto_id' => 28,
                'descripcion' => '',
                'peso' => 0,
                'unidad_medida_id' => 32,
                'cantidad' => 1.0,
                'codigo_barras' => '10000000032',
                'estado_producto_id' => 50,
                'categoria_id' => 65,
                'marca_id' => null,
                'contrato_convenio_id' => 1,
                'ambiente_id' => 1,
                'proveedor_id' => 1,
                'fecha_vencimiento' => null,
                'imagen' => 'img/inventario/producto-default.png',
                'user_create_id' => 1, 
                'user_update_id' => 1,
            ],
            [
                'producto' => 'FLOCULANTE DE SUELOS',
                'tipo_producto_id' => 28,
                'descripcion' => 'Dos frascos de 60 mililitros',
                'peso' => 0,
                'unidad_medida_id' => 36,
                'cantidad' => 120.0,
                'codigo_barras' => '10000000033',
                'estado_producto_id' => 50,
                'categoria_id' => 65,
                'marca_id' => 68,
                'contrato_convenio_id' => 1,
                'ambiente_id' => 1,
                'proveedor_id' => 1,
                'fecha_vencimiento' => null,
                'imagen' => 'img/inventario/producto-default.png',
                'user_create_id' => 1, 
                'user_update_id' => 1,
            ],
            [
                'producto' => 'DISPERSION DE TEXTURA',
                'tipo_producto_id' => 28,
                'descripcion' => '',
                'peso' => 0,
                'unidad_medida_id' => 36,
                'cantidad' => 60.0,
                'codigo_barras' => '10000000034',
                'estado_producto_id' => 50,
                'categoria_id' => 65,
                'marca_id' => 68,
                'contrato_convenio_id' => 1,
                'ambiente_id' => 1,
                'proveedor_id' => 1,
                'fecha_vencimiento' => null,
                'imagen' => 'img/inventario/producto-default.png',
                'user_create_id' => 1, 
                'user_update_id' => 1,
            ],
            [
                'producto' => 'SLUCION FLOCULANTE DE TRICON',
                'tipo_producto_id' => 28,
                'descripcion' => 'Frasco de 120 mililitros',
                'peso' => 0,
                'unidad_medida_id' => 36,
                'cantidad' => 60.0,
                'codigo_barras' => '10000000035',
                'estado_producto_id' => 50,
                'categoria_id' => 65,
                'marca_id' => 68,
                'contrato_convenio_id' => 1,
                'ambiente_id' => 1,
                'proveedor_id' => 1,
                'fecha_vencimiento' => null,
                'imagen' => 'img/inventario/producto-default.png',
                'user_create_id' => 1, 
                'user_update_id' => 1,
            ],
            [
                'producto' => 'SOLUCION DE EXTRACCION UNIVERSAL',
                'tipo_producto_id' => 28,
                'descripcion' => '3 Frascos 250 mililitros - 2 Frascos de 120 mililitros',
                'peso' => 0,
                'unidad_medida_id' => 36,
                'cantidad' => 300.0,
                'codigo_barras' => '10000000036',
                'estado_producto_id' => 50,
                'categoria_id' => 65,
                'marca_id' => 68,
                'contrato_convenio_id' => 1,
                'ambiente_id' => 1,
                'proveedor_id' => 1,
                'fecha_vencimiento' => null,
                'imagen' => 'img/inventario/producto-default.png',
                'user_create_id' => 1, 
                'user_update_id' => 1,
            ],
            [
                'producto' => 'INDICADOR DE PH TRICON',
                'tipo_producto_id' => 28,
                'descripcion' => '',
                'peso' => 0,
                'unidad_medida_id' => 41,
                'cantidad' => 1.0,
                'codigo_barras' => '10000000037',
                'estado_producto_id' => 50,
                'categoria_id' => 65,
                'marca_id' => 68,
                'contrato_convenio_id' => 1,
                'ambiente_id' => 1,
                'proveedor_id' => 1,
                'fecha_vencimiento' => null,
                'imagen' => 'img/inventario/producto-default.png',
                'user_create_id' => 1, 
                'user_update_id' => 1,
            ],
            [
                'producto' => 'REACTIVO DE FOSFORO #2',
                'tipo_producto_id' => 28,
                'descripcion' => '2 Frascos de 30 mililitros',
                'peso' => 0,
                'unidad_medida_id' => 36,
                'cantidad' => 40.0,
                'codigo_barras' => '10000000038',
                'estado_producto_id' => 50,
                'categoria_id' => 65,
                'marca_id' => 68,
                'contrato_convenio_id' => 1,
                'ambiente_id' => 1,
                'proveedor_id' => 1,
                'fecha_vencimiento' => null,
                'imagen' => 'img/inventario/producto-default.png',
                'user_create_id' => 1, 
                'user_update_id' => 1,
            ],
            [
                'producto' => 'REACTIVO DE NITRATO #1',
                'tipo_producto_id' => 28,
                'descripcion' => '2 Frascos de 30 mililitros',
                'peso' => 0,
                'unidad_medida_id' => 36,
                'cantidad' => 15.0,
                'codigo_barras' => '10000000039',
                'estado_producto_id' => 50,
                'categoria_id' => 65,
                'marca_id' => 68,
                'contrato_convenio_id' => 1,
                'ambiente_id' => 1,
                'proveedor_id' => 1,
                'fecha_vencimiento' => null,
                'imagen' => 'img/inventario/producto-default.png',
                'user_create_id' => 1, 
                'user_update_id' => 1,
            ],
            [
                'producto' => 'REACTIVO DE NITRATO #2',
                'tipo_producto_id' => 28,
                'descripcion' => 'Frasco de 30 gramos',
                'peso' => 0,
                'unidad_medida_id' => 30,
                'cantidad' => 1.0,
                'codigo_barras' => '10000000040',
                'estado_producto_id' => 50,
                'categoria_id' => 65,
                'marca_id' => 68,
                'contrato_convenio_id' => 1,
                'ambiente_id' => 1,
                'proveedor_id' => 1,
                'fecha_vencimiento' => null,
                'imagen' => 'img/inventario/producto-default.png',
                'user_create_id' => 1, 
                'user_update_id' => 1,
            ],
            [
                'producto' => 'REACTIVO DE POTASIO C',
                'tipo_producto_id' => 28,
                'descripcion' => '1 Frasco de 25 mililitros - 1 frasco de 120 mililitros',
                'peso' => 0,
                'unidad_medida_id' => 36,
                'cantidad' => 60.0,
                'codigo_barras' => '10000000041',
                'estado_producto_id' => 50,
                'categoria_id' => 65,
                'marca_id' => 68,
                'contrato_convenio_id' => 1,
                'ambiente_id' => 1,
                'proveedor_id' => 1,
                'fecha_vencimiento' => null,
                'imagen' => 'img/inventario/producto-default.png',
                'user_create_id' => 1, 
                'user_update_id' => 1,
            ],
            [
                'producto' => 'TEST DE SOLUCION DE MAGNESIO #1',
                'tipo_producto_id' => 28,
                'descripcion' => 'Frasco de 30 mililitros.',
                'peso' => 0,
                'unidad_medida_id' => 36,
                'cantidad' => 30.0,
                'codigo_barras' => '10000000042',
                'estado_producto_id' => 50,
                'categoria_id' => 65,
                'marca_id' => 68,
                'contrato_convenio_id' => 1,
                'ambiente_id' => 1,
                'proveedor_id' => 1,
                'fecha_vencimiento' => null,
                'imagen' => 'img/inventario/producto-default.png',
                'user_create_id' => 1, 
                'user_update_id' => 1,
            ],
            [
                'producto' => 'TEST DE SOLUCION DE CALCIO',
                'tipo_producto_id' => 28,
                'descripcion' => 'Frasco de 30 mililitros',
                'peso' => 0,
                'unidad_medida_id' => 36,
                'cantidad' => 30.0,
                'codigo_barras' => '10000000043',
                'estado_producto_id' => 50,
                'categoria_id' => 65,
                'marca_id' => 68,
                'contrato_convenio_id' => 1,
                'ambiente_id' => 1,
                'proveedor_id' => 1,
                'fecha_vencimiento' => null,
                'imagen' => 'img/inventario/producto-default.png',
                'user_create_id' => 1, 
                'user_update_id' => 1,
            ],
            [
                'producto' => 'TEST DE SOLUCION DE MAGNESIO  #2',
                'tipo_producto_id' => 28,
                'descripcion' => 'Frasco de 30 mililitros.',
                'peso' => 0,
                'unidad_medida_id' => 36,
                'cantidad' => 30.0,
                'codigo_barras' => '10000000044',
                'estado_producto_id' => 50,
                'categoria_id' => 65,
                'marca_id' => 68,
                'contrato_convenio_id' => 1,
                'ambiente_id' => 1,
                'proveedor_id' => 1,
                'fecha_vencimiento' => null,
                'imagen' => 'img/inventario/producto-default.png',
                'user_create_id' => 1, 
                'user_update_id' => 1,
            ],
            [
                'producto' => 'INDICADOR ROJO DE CLORFENOL',
                'tipo_producto_id' => 28,
                'descripcion' => 'Frasco de 15 mililitros',
                'peso' => 0,
                'unidad_medida_id' => 36,
                'cantidad' => 15.0,
                'codigo_barras' => '10000000045',
                'estado_producto_id' => 50,
                'categoria_id' => 65,
                'marca_id' => 68,
                'contrato_convenio_id' => 1,
                'ambiente_id' => 1,
                'proveedor_id' => 1,
                'fecha_vencimiento' => null,
                'imagen' => 'img/inventario/producto-default.png',
                'user_create_id' => 1, 
                'user_update_id' => 1,
            ],
            [
                'producto' => 'INDICADOR AZUL DE TIMOL',
                'tipo_producto_id' => 28,
                'descripcion' => 'Frasco de 15 mililitros',
                'peso' => 0,
                'unidad_medida_id' => 36,
                'cantidad' => 15.0,
                'codigo_barras' => '10000000046',
                'estado_producto_id' => 50,
                'categoria_id' => 65,
                'marca_id' => 68,
                'contrato_convenio_id' => 1,
                'ambiente_id' => 1,
                'proveedor_id' => 1,
                'fecha_vencimiento' => null,
                'imagen' => 'img/inventario/producto-default.png',
                'user_create_id' => 1, 
                'user_update_id' => 1,
            ],
            [
                'producto' => 'INDICADOR DVERDE DE BRONQUESOL',
                'tipo_producto_id' => 28,
                'descripcion' => 'Frasco de 15 mililitos',
                'peso' => 0,
                'unidad_medida_id' => 36,
                'cantidad' => 15.0,
                'codigo_barras' => '10000000047',
                'estado_producto_id' => 50,
                'categoria_id' => 65,
                'marca_id' => 68,
                'contrato_convenio_id' => 1,
                'ambiente_id' => 1,
                'proveedor_id' => 1,
                'fecha_vencimiento' => null,
                'imagen' => 'img/inventario/producto-default.png',
                'user_create_id' => 1, 
                'user_update_id' => 1,
            ],
            [
                'producto' => 'BOTELLA DESMINERILIZADORA',
                'tipo_producto_id' => 28,
                'descripcion' => 'Frasco de 250 mililitros',
                'peso' => 0,
                'unidad_medida_id' => 36,
                'cantidad' => 250.0,
                'codigo_barras' => '10000000048',
                'estado_producto_id' => 50,
                'categoria_id' => 65,
                'marca_id' => 68,
                'contrato_convenio_id' => 1,
                'ambiente_id' => 1,
                'proveedor_id' => 1,
                'fecha_vencimiento' => null,
                'imagen' => 'img/inventario/producto-default.png',
                'user_create_id' => 1, 
                'user_update_id' => 1,
            ],
            [
                'producto' => 'REACTIVO PARA DETECCION DE HUMUS',
                'tipo_producto_id' => 28,
                'descripcion' => 'Frasco de 50 gramos',
                'peso' => 0,
                'unidad_medida_id' => 30,
                'cantidad' => 15.0,
                'codigo_barras' => '10000000049',
                'estado_producto_id' => 50,
                'categoria_id' => 65,
                'marca_id' => 68,
                'contrato_convenio_id' => 1,
                'ambiente_id' => 1,
                'proveedor_id' => 1,
                'fecha_vencimiento' => null,
                'imagen' => 'img/inventario/producto-default.png',
                'user_create_id' => 1, 
                'user_update_id' => 1,
            ],
            [
                'producto' => 'REACTIVO DE POTASIO TABLETAS B',
                'tipo_producto_id' => 28,
                'descripcion' => 'Tableta x 10 pastillas',
                'peso' => 0,
                'unidad_medida_id' => 47,
                'cantidad' => 2.0,
                'codigo_barras' => '10000000050',
                'estado_producto_id' => 50,
                'categoria_id' => 65,
                'marca_id' => 68,
                'contrato_convenio_id' => 1,
                'ambiente_id' => 1,
                'proveedor_id' => 1,
                'fecha_vencimiento' => null,
                'imagen' => 'img/inventario/producto-default.png',
                'user_create_id' => 1, 
                'user_update_id' => 1,
            ],
                      
         ];
        foreach ($productos as $producto){
            Producto::create($producto);
        }
    }
}
