<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Inventario\Producto;

class ProductoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $productos = [
            [
                'producto' => 'PRODUCTO 1',
                'tipo_producto_id' => 28,
                'descripcion' => 'DESCRIPCIÓN DE PRUEBA DEL PRODUCTO 1',
                'peso' => 15,
                'unidad_medida_id' => 31,
                'cantidad' => 4,
                'codigo_barras' => '10000000001',
                'estado_producto_id' => 50,
                'categoria_id' => 59,
                'marca_id' => 68,
                'contrato_convenio_id' => 1,
                'ambiente_id' => 1,
                'proveedor_id' => 1,
                'fecha_vencimiento' => '2025-12-31',
                'imagen' => 'img/inventario/producto-default.png',
                'user_create_id' => 1, 
                'user_update_id' => 1,
            ],
            [
                'producto' => 'PRODUCTO 2',
                'tipo_producto_id' => 28,
                'descripcion' => 'DESCRIPCIÓN DE PRUEBA DEL PRODUCTO 2',
                'peso' => 20,
                'unidad_medida_id' => 32,
                'cantidad' => 8,
                'codigo_barras' => '10000000002',
                'estado_producto_id' => 50,
                'categoria_id' => 60,
                'marca_id' => 69,
                'contrato_convenio_id' => 2,
                'ambiente_id' => 2,
                'proveedor_id' => 2,
                'fecha_vencimiento' => '2025-11-21',
                'imagen' => 'img/inventario/producto-default.png',
                'user_create_id' => 1, 
                'user_update_id' => 1,
            ],
            [
                'producto' => 'PRODUCTO 3',
                'tipo_producto_id' => 28,
                'descripcion' => 'DESCRIPCIÓN DE PRUEBA DEL PRODUCTO 3',
                'peso' => 500,
                'unidad_medida_id' => 30,
                'cantidad' => 50,
                'codigo_barras' => '10000000003',
                'estado_producto_id' => 50,
                'categoria_id' => 61,
                'marca_id' => 70,
                'contrato_convenio_id' => 3,
                'ambiente_id' => 3,
                'proveedor_id' => 3,
                'fecha_vencimiento' => '2025-01-12',
                'imagen' => 'img/inventario/producto-default.png',
                'user_create_id' => 1, 
                'user_update_id' => 1,
            ],
            [
                'producto' => 'PRODUCTO 4',
                'tipo_producto_id' => 28,
                'descripcion' => 'DESCRIPCIÓN DE PRUEBA DEL PRODUCTO 4',
                'peso' => 1000,
                'unidad_medida_id' => 30,
                'cantidad' => 32,
                'codigo_barras' => '10000000004',
                'estado_producto_id' => 50,
                'categoria_id' => 66,
                'marca_id' => 75,
                'contrato_convenio_id' => 4,
                'ambiente_id' => 4,
                'proveedor_id' => 4,
                'fecha_vencimiento' => '2025-12-31',
                'imagen' => 'img/inventario/producto-default.png',
                'user_create_id' => 1, 
                'user_update_id' => 1,
            ],
            [
                'producto' => 'PRODUCTO 5',
                'tipo_producto_id' => 29,
                'descripcion' => 'DESCRIPCIÓN DE PRUEBA DEL PRODUCTO 5',
                'peso' => 20,
                'unidad_medida_id' => 41,
                'cantidad' => 6,
                'codigo_barras' => '10000000005',
                'estado_producto_id' => 50,
                'categoria_id' => 65,
                'marca_id' => 73,
                'contrato_convenio_id' => 5,
                'ambiente_id' => 5,
                'proveedor_id' => 5,
                'fecha_vencimiento' => '2025-12-31',
                'imagen' => 'img/inventario/producto-default.png',
                'user_create_id' => 1, 
                'user_update_id' => 1,
            ],
            [
                'producto' => 'PRODUCTO 6',
                'tipo_producto_id' => 28,
                'descripcion' => 'DESCRIPCIÓN DE PRUEBA DEL PRODUCTO 6',
                'peso' => 100,
                'unidad_medida_id' => 36,
                'cantidad' => 9,
                'codigo_barras' => '10000000006',
                'estado_producto_id' => 50,
                'categoria_id' => 59,
                'marca_id' => 68,
                'contrato_convenio_id' => 6,
                'ambiente_id' => 6,
                'proveedor_id' => 1,
                'fecha_vencimiento' => '2025-12-31',
                'imagen' => 'img/inventario/producto-default.png',
                'user_create_id' => 1, 
                'user_update_id' => 1,
            ],
            [
                'producto' => 'PRODUCTO 7',
                'tipo_producto_id' => 29,
                'descripcion' => 'DESCRIPCIÓN DE PRUEBA DEL PRODUCTO 7',
                'peso' => 11,
                'unidad_medida_id' => 41,
                'cantidad' => 10,
                'codigo_barras' => '10000000007',
                'estado_producto_id' => 50,
                'categoria_id' => 60,
                'marca_id' => 69,
                'contrato_convenio_id' => 7,
                'ambiente_id' => 7,
                'proveedor_id' => 2,
                'fecha_vencimiento' => '2025-12-31',
                'imagen' => 'img/inventario/producto-default.png',
                'user_create_id' => 1, 
                'user_update_id' => 1,
            ],
            [
                'producto' => 'PRODUCTO 8',
                'tipo_producto_id' => 28,
                'descripcion' => 'DESCRIPCIÓN DE PRUEBA DEL PRODUCTO 8',
                'peso' => 2000,
                'unidad_medida_id' => 30,
                'cantidad' => 35,
                'codigo_barras' => '10000000008',
                'estado_producto_id' => 50,
                'categoria_id' => 61,
                'marca_id' => 70,
                'contrato_convenio_id' => 8,
                'ambiente_id' => 8,
                'proveedor_id' => 3,
                'fecha_vencimiento' => '2025-12-31',
                'imagen' => 'img/inventario/producto-default.png',
                'user_create_id' => 1, 
                'user_update_id' => 1,
            ],
            [
                'producto' => 'PRODUCTO 9',
                'tipo_producto_id' => 28,
                'descripcion' => 'DESCRIPCIÓN DE PRUEBA DEL PRODUCTO 9',
                'peso' => 1.5,
                'unidad_medida_id' => 37,
                'cantidad' => 29,
                'codigo_barras' => '10000000009',
                'estado_producto_id' => 50,
                'categoria_id' => 62,
                'marca_id' => 71,
                'contrato_convenio_id' => 9,
                'ambiente_id' => 9,
                'proveedor_id' => 4,
                'fecha_vencimiento' => '2025-12-31',
                'imagen' => 'img/inventario/producto-default.png',
                'user_create_id' => 1, 
                'user_update_id' => 1,
            ],
            [
                'producto' => 'PRODUCTO 10',
                'tipo_producto_id' => 28,
                'descripcion' => 'DESCRIPCIÓN DE PRUEBA DEL PRODUCTO 10',
                'peso' => 2,
                'unidad_medida_id' => 32,
                'cantidad' => 10,
                'codigo_barras' => '10000000010',
                'estado_producto_id' => 50,
                'categoria_id' => 67,
                'marca_id' => 72,
                'contrato_convenio_id' => 10,
                'ambiente_id' => 10,
                'proveedor_id' => 5,
                'fecha_vencimiento' => '2025-12-31',
                'imagen' => 'img/inventario/producto-default.png',
                'user_create_id' => 1, 
                'user_update_id' => 1,
            ],
        ];
        foreach ($productos as $producto){
            Producto::create($producto);
        }
    }
}
