<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\ResultadosAprendizaje;
use Database\Seeders\Concerns\TruncatesTables;

class ResultadosAprendizajeSeeder extends Seeder
{
    use TruncatesTables;

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $this->truncateModel(ResultadosAprendizaje::class);

        $resultados_aprendizajes = [
            [
                'id' => 1,
                'codigo' => '593109 - 03',
                'nombre' => 'DOCUMENTAR EL PROCESO DE IMPLANTACIÓN DE SOFTWARE SIGUIENDO ESTÁNDARES DE CALIDAD.',
                'duracion' => 36,
                'fecha_inicio' => '2026-01-01',
                'fecha_fin' => '2026-01-01',
                'status' => 1,
                'user_create_id' => 1,
                'user_edit_id' => 1,
            ],
            [
                'id' => 2,
                'codigo' => '593110 - 02',
                'nombre' => 'DESPLEGAR EL SOFTWARE DE ACUERDO CON LA ARQUITECTURA Y LAS POLÍTICAS ESTABLECIDAS.',
                'duracion' => 36,
                'fecha_inicio' => '2026-01-01',
                'fecha_fin' => '2026-01-01',
                'user_create_id' => 1,
                'user_edit_id' => 1,
            ],
            [
                'id' => 3,
                'codigo' => '593111 - 01',
                'nombre' => 'PLANEAR ACTIVIDADES DE IMPLANTACIÓN DEL SOFTWARE DE ACUERDO CON LAS CONDICIONES DEL SISTEMA.',
                'duracion' => 36,
                'fecha_inicio' => '2026-01-01',
                'fecha_fin' => '2026-01-01',
                'user_create_id' => 1,
                'user_edit_id' => 1,
            ],
            [
                'id' => 4,
                'codigo' => '593112 - 04',
                'nombre' => 'IMPLANTAR EL SOFTWARE DE ACUERDO CON LOS NIVELES DE SERVICIO ESTABLECIDOS CON EL CLIENTE.',
                'duracion' => 36,
                'fecha_inicio' => '2026-01-01',
                'fecha_fin' => '2026-01-01',
                'user_create_id' => 1,
                'user_edit_id' => 1,
            ],
            [
                'id' => 5,
                'codigo' => '593144 - 02',
                'nombre' => 'VERIFICAR LA CALIDAD DEL SOFTWARE DE ACUERDO CON LAS PRÁCTICAS ASOCIADAS EN LOS PROCESOS DE DESARROLLO.',
                'duracion' => 48,
                'fecha_inicio' => '2026-01-01',
                'fecha_fin' => '2026-01-01',
                'user_create_id' => 1,
                'user_edit_id' => 1,
            ],
            [
                'id' => 6,
                'codigo' => '593145 - 03',
                'nombre' => 'REALIZAR ACTIVIDADES DE MEJORA DE LA CALIDAD DEL SOFTWARE A PARTIR DE LOS RESULTADOS DE LA VERIFICACIÓN.',
                'duracion' => 48,
                'fecha_inicio' => '2026-01-01',
                'fecha_fin' => '2026-01-01',
                'user_create_id' => 1,
                'user_edit_id' => 1,
            ],
            [
                'id' => 7,
                'codigo' => '593146 - 01',
                'nombre' => 'INCORPORAR ACTIVIDADES DE ASEGURAMIENTO DE LA CALIDAD DEL SOFTWARE DE ACUERDO CON ESTÁNDARES DE LA INDUSTRIA.',
                'duracion' => 48,
                'fecha_inicio' => '2026-01-01',
                'fecha_fin' => '2026-01-01',
                'user_create_id' => 1,
                'user_edit_id' => 1,
            ],
            [
                'id' => 8,
                'codigo' => '593152 - 04',
                'nombre' => 'OPTIMIZAR LOS RESULTADOS, DE ACUERDO CON LA VERIFICACIÓN.',
                'duracion' => 12,
                'fecha_inicio' => '2024-04-04',
                'fecha_fin' => '2024-05-06',
                'user_create_id' => 1,
                'user_edit_id' => 1,
            ],
            [
                'id' => 9,
                'codigo' => '593154 - 01',
                'nombre' => 'ALISTAR HERRAMIENTAS DE TECNOLOGÍAS DE LA INFORMACIÓN Y LA COMUNICACIÓN (TIC), DE ACUERDO CON LAS NECESIDADES DE PROCESAMIENTO DE INFORMACIÓN Y COMUNICACIÓN.',
                'duracion' => 12,
                'fecha_inicio' => '2024-04-26',
                'fecha_fin' => '2024-04-29',
                'user_create_id' => 1,
                'user_edit_id' => 1,
            ],
            [
                'id' => 10,
                'codigo' => '593151 - 02',
                'nombre' => 'APLICAR FUNCIONALIDADES DE HERRAMIENTAS Y SERVICIOS TIC, DE ACUERDO CON MANUALES DE USO, PROCEDIMIENTOS ESTABLECIDOS Y BUENAS PRÁCTICAS.',
                'duracion' => 12,
                'fecha_inicio' => '2024-04-30',
                'fecha_fin' => '2024-05-03',
                'user_create_id' => 1,
                'user_edit_id' => 1,
            ],
            [
                'id' => 11,
                'codigo' => '593153 - 03',
                'nombre' => 'EVALUAR LOS RESULTADOS, DE ACUERDO CON LOS REQUERIMIENTOS.',
                'duracion' => 12,
                'fecha_inicio' => '2024-05-07',
                'fecha_fin' => '2024-05-10',
                'user_create_id' => 1,
                'user_edit_id' => 1,
            ],
            [
                'id' => 12,
                'codigo' => '593346 - 01',
                'nombre' => 'CARACTERIZAR LOS PROCESOS DE LA ORGANIZACIÓN DE ACUERDO CON EL SOFTWARE A CONSTRUIR.',
                'duracion' => 36,
                'fecha_inicio' => '2024-05-11',
                'fecha_fin' => '2024-05-18',
                'user_create_id' => 1,
                'user_edit_id' => 1,
            ],
            [
                'id' => 13,
                'codigo' => '593344 - 02',
                'nombre' => 'RECOLECTAR INFORMACIÓN DEL SOFTWARE A CONSTRUIR DE ACUERDO CON LAS NECESIDADES DEL CLIENTE.',
                'duracion' => 36,
                'fecha_inicio' => '2024-05-24',
                'fecha_fin' => '2024-06-01',
                'user_create_id' => 1,
                'user_edit_id' => 1,
            ],
            [
                'id' => 14,
                'codigo' => '593347 - 03',
                'nombre' => 'ESTABLECER LOS REQUISITOS DEL SOFTWARE DE ACUERDO CON LA INFORMACIÓN RECOLECTADA.',
                'duracion' => 36,
                'fecha_inicio' => '2024-06-04',
                'fecha_fin' => '2024-06-15',
                'user_create_id' => 1,
                'user_edit_id' => 1,
            ],
            [
                'id' => 15,
                'codigo' => '593345 - 04',
                'nombre' => 'VALIDAR EL INFORME DE REQUISITOS DE ACUERDO CON LAS NECESIDADES DEL CLIENTE.',
                'duracion' => 36,
                'fecha_inicio' => '2024-06-17',
                'fecha_fin' => '2024-06-25',
                'user_create_id' => 1,
                'user_edit_id' => 1,
            ],
            [
                'id' => 16,
                'codigo' => '592375 - 01',
                'nombre' => 'PLANEAR ACTIVIDADES DE ANÁLISIS DE ACUERDO CON LA METODOLOGÍA SELECCIONADA.',
                'duracion' => 72,
                'fecha_inicio' => '2024-06-28',
                'fecha_fin' => '2024-07-23',
                'user_create_id' => 1,
                'user_edit_id' => 1,
            ],
            [
                'id' => 17,
                'codigo' => '592373 - 02',
                'nombre' => 'MODELAR LAS FUNCIONES DEL SOFTWARE DE ACUERDO CON EL INFORME DE REQUISITOS.',
                'duracion' => 72,
                'fecha_inicio' => '2024-07-26',
                'fecha_fin' => '2024-08-12',
                'user_create_id' => 1,
                'user_edit_id' => 1,
            ],
            [
                'id' => 18,
                'codigo' => '592376 - 03',
                'nombre' => 'DESARROLLAR PROCESOS LÓGICOS A TRAVÉS DE LA IMPLEMENTACIÓN DE ALGORITMOS.',
                'duracion' => 72,
                'fecha_inicio' => '2024-08-13',
                'fecha_fin' => '2024-09-02',
                'user_create_id' => 1,
                'user_edit_id' => 1,
            ],
            [
                'id' => 19,
                'codigo' => '592374 - 04',
                'nombre' => 'VERIFICAR LOS MODELOS REALIZADOS EN LA FASE DE ANÁLISIS DE ACUERDO CON LO ESTABLECIDO EN EL INFORME DE REQUISITOS.',
                'duracion' => 72,
                'fecha_inicio' => '2024-09-03',
                'fecha_fin' => '2024-09-21',
                'user_create_id' => 1,
                'user_edit_id' => 1,
            ],
            [
                'id' => 20,
                'codigo' => '593060 - 01',
                'nombre' => 'DEFINIR ESPECIFICACIONES TÉCNICAS DEL SOFTWARE DE ACUERDO CON LAS CARACTERÍSTICAS DEL SOFTWARE A CONSTRUIR.',
                'duracion' => 16,
                'fecha_inicio' => '2024-09-23',
                'fecha_fin' => '2024-10-07',
                'user_create_id' => 1,
                'user_edit_id' => 1,
            ],
            [
                'id' => 21,
                'codigo' => '593062 - 02',
                'nombre' => 'ELABORAR PROPUESTA TÉCNICA DEL SOFTWARE DE ACUERDO CON LAS ESPECIFICACIONES TÉCNICAS DEFINIDAS.',
                'duracion' => 16,
                'fecha_inicio' => '2024-10-08',
                'fecha_fin' => '2024-10-22',
                'user_create_id' => 1,
                'user_edit_id' => 1,
            ],
            [
                'id' => 22,
                'codigo' => '593061 - 03',
                'nombre' => 'VALIDAR LAS CONDICIONES DE LA PROPUESTA TÉCNICA DEL SOFTWARE DE ACUERDO CON LOS INTERESES DE LAS PARTES.',
                'duracion' => 16,
                'fecha_inicio' => '2024-10-25',
                'fecha_fin' => '2024-11-08',
                'user_create_id' => 1,
                'user_edit_id' => 1,
            ],
            [
                'id' => 23,
                'codigo' => '593103 - 01',
                'nombre' => 'ELABORAR LOS ARTEFACTOS DE DISEÑO DEL SOFTWARE SIGUIENDO LAS PRÁCTICAS DE LA METODOLOGÍA SELECCIONADA.',
                'duracion' => 84,
                'fecha_inicio' => '2024-11-09',
                'fecha_fin' => '2024-12-02',
                'user_create_id' => 1,
                'user_edit_id' => 1,
            ],
                        [
                'id' => 24,
                'codigo' => '593101 - 02',
                'nombre' => 'ESTRUCTURAR EL MODELO DE DATOS DEL SOFTWARE DE ACUERDO CON LAS ESPECIFICACIONES DEL ANÁLISIS.',
                'duracion' => 84,
                'fecha_inicio' => '2025-02-03',
                'fecha_fin' => '2025-02-24',
                'user_create_id' => 1,
                'user_edit_id' => 1,
            ],
                        [
                'id' => 25,
                'codigo' => '593100 - 03',
                'nombre' => 'DETERMINAR LAS CARACTERÍSTICAS TÉCNICAS DE LA INTERFAZ GRÁFICA DEL SOFTWARE ADOPTANDO ESTÁNDARES.',
                'duracion' => 84,
                'fecha_inicio' => '2025-02-25',
                'fecha_fin' => '2025-03-18',
                'user_create_id' => 1,
                'user_edit_id' => 1,
            ],
                        [
                'id' => 26,
                'codigo' => '593102 - 04',
                'nombre' => 'VERIFICAR LOS ENTREGABLES DE LA FASE DE DISEÑO DEL SOFTWARE DE ACUERDO CON LO ESTABLECIDO EN EL INFORME DE ANÁLISIS.',
                'duracion' => 84,
                'fecha_inicio' => '2025-03-21',
                'fecha_fin' => '2025-04-12',
                'user_create_id' => 1,
                'user_edit_id' => 1,
            ],
                        [
                'id' => 27,
                'codigo' => '593106 - 01',
                'nombre' => 'PLANEAR ACTIVIDADES DE CONSTRUCCIÓN DEL SOFTWARE DE ACUERDO CON EL DISEÑO ESTABLECIDO.',
                'duracion' => 201.6,
                'fecha_inicio' => '2025-04-21',
                'fecha_fin' => '2025-06-20',
                'user_create_id' => 1,
                'user_edit_id' => 1,
            ],
                        [
                'id' => 28,
                'codigo' => '593107 - 02',
                'nombre' => 'CONSTRUIR LA BASE DE DATOS PARA EL SOFTWARE A PARTIR DEL MODELO DE DATOS.',
                'duracion' => 201.6,
                'fecha_inicio' => '2025-06-21',
                'fecha_fin' => '2025-08-30',
                'user_create_id' => 1,
                'user_edit_id' => 1,
            ],
                        [
                'id' => 29,
                'codigo' => '593104 - 03',
                'nombre' => 'CREAR COMPONENTES FRONT-END DEL SOFTWARE DE ACUERDO CON EL DISEÑO.',
                'duracion' => 201.6,
                'fecha_inicio' => '2025-09-01',
                'fecha_fin' => '2025-10-31',
                'user_create_id' => 1,
                'user_edit_id' => 1,
            ],
                        [
                'id' => 30,
                'codigo' => '593108 - 04',
                'nombre' => 'CODIFICAR EL SOFTWARE DE ACUERDO CON EL DISEÑO ESTABLECIDO.',
                'duracion' => 201.6,
                'fecha_inicio' => '2025-11-01',
                'fecha_fin' => '2025-12-13',
                'user_create_id' => 1,
                'user_edit_id' => 1,
            ],

            [
                'id' => 31,
                'codigo' => '593105 - 05',
                'nombre' => 'REALIZAR PRUEBAS AL SOFTWARE PARA VERIFICAR SU FUNCIONALIDAD.',
                'duracion' => 201.6,
                'fecha_inicio' => '2026-01-01',
                'fecha_fin' => '2026-01-01',
                'user_create_id' => 1,
                'user_edit_id' => 1,
            ],
        ];

        foreach ($resultados_aprendizajes as $resultados_aprendizaje) {
            // Agregar status por defecto si no existe
            if (!isset($resultados_aprendizaje['status'])) {
                $resultados_aprendizaje['status'] = 1;
            }
            ResultadosAprendizaje::create($resultados_aprendizaje);
        }
    }
}